# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunes Search API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunes Search API
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 4.0.0-beta.6'

  target 'iTunes Search APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iTunes Search APIUITests' do
    # Pods for testing
  end

end
